---
- hosts: localhost
  tasks:
    - name: Update cache
      apt:
       update_cache: yes

    - name: Upgrade all packages on servers
      apt:
        name: "*"
        state: latest
      when: ansible_distribution == "ubuntu"
    - name: Upgrade all packages
      yum:
        name: "*"
        state: latest
      when: ansible_distribution == "Redhat"

